# -*- coding: utf-8 -*-
"""calc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8brXPDhiZB8LJUlaBoGc3LXtJzzgrMh

# **Calc Module**
"""

def get_add(a, b):

    """Addition Function"""

    return a + b

def get_substract(a, b):

    """Substract Function"""

    return a - b

def get_multiply(a,b):

    """Multiply Function"""

    return a * b

def get_divide(a, b):

    """Divide Function"""

    if b == 0 :

        raise ZeroDivisionError("Can not divide by zero")

    return a / b